name = "vetoliiga-worldcup-proxy"
main = "cloudflare-worker.js"
compatibility_date = "2026-06-26"
workers_dev = true

[vars]
FIREBASE_PROJECT_ID = "vetoliigan-kisaveikkaus-2026"
TELEGRAM_CHAT_ID = "-1001048034441"
TELEGRAM_PLAYER_MENTIONS = '{"Joni":"@jonironimus","Ilpo":"@ilippos","Sami":"@samikarki","Santeri":"@Santeri"}'
TELEGRAM_PLAYER_IDENTITIES = '{"Joni":["jonironimus","Joni"],"Ilpo":["ilippos","Ilpo"],"Sami":["samikarki","Sami"],"Santeri":["Santeri"]}'

[triggers]
crons = ["*/5 * * * *"]

[observability]
enabled = true
